spring:
  application:
    name: client-service
  datasource:
    url: jdbc:h2:mem:clientdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8081

spring:
  config:
    import: "optional:consul:discovery:8500"
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        service-name: client-service
        prefer-ip-address: true