server:
  port: 8082

spring:
  application:
    name: voiture-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

spring:
  config:
    import: "optional:consul:discovery:8500"
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        service-name: voiture-service
        prefer-ip-address: true
